require:
  - rubocop-performance

inherit_mode:
  merge:
    - Include
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
    - <%= path.sub(/^!! /, '') %>
    <% end %>
    - Task.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
